# Generated by Django 3.1.4 on 2020-12-24 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_text',
            new_name='text_of_event',
        ),
    ]
