# Generated by Django 3.1.4 on 2020-12-24 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201224_0418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_image',
            new_name='image_of_event',
        ),
    ]
