# Generated by Django 3.1.4 on 2020-12-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=50)),
                ('date_of_post', models.DateField(auto_now=True)),
                ('text_post', models.TextField()),
                ('image_post', models.ImageField(upload_to='blog_images/')),
            ],
        ),
    ]
