# Generated by Django 3.1.4 on 2020-12-22 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text_post',
            new_name='Entry',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image_post',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_title',
            new_name='Title',
        ),
    ]
