# Generated by Django 3.1.4 on 2020-12-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201222_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_of_post',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
