# Generated by Django 3.1.4 on 2020-12-24 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201222_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_of_post',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Entry',
            new_name='entry',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Title',
            new_name='title',
        ),
    ]
